DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS resins;
DROP TABLE IF EXISTS rocks;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author_name TEXT NOT NULL,
  pages INT NOT NULL
);

CREATE TABLE resins (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  source_taxonomy TEXT NOT NULL,
  predominant_chemicals TEXT [] NOT NULL
);

CREATE TABLE rocks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  mohs_hardness INT NOT NULL,
  composition TEXT NOT NULL
);